name: JMeter Performance Test

on:
  # workflow_dispatch:  # Ejecutamos el Workflow manualmente
  push:                 # Ejecutamos el Workflow al hacer push
    branches:
      - master

jobs:
  performance-test:
    # Ultima version de ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo fuente del repositorio
        uses: actions/checkout@v4

      - name: Configurar el entorno Java 
        uses: actions/setup-java@v4
        with:
          distribution: temurin # Distribucion OpenJDK de Eclipse (Recomendada)
          java-version: 21      # Version 21 LTS

      - name: Descargar e instalar JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Ejecutar plan de pruebas
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter \
          -n \
          -t test-plans/plan.jmx \
          -l results.jtl \
          -e \
          -o report

      - name: Guardar reporte HTML
        uses: actions/upload-artifact@v4
        with:
          name: JMeter-Report
          path: report

      - name: Guardar resultados JTL
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: results.jtl